language: java
jdk: oraclejdk8

install:
  - echo "Overriding default Travis install step to avoid unnecessary './gradlew assemble'."

script:
  - ./gradlew clean check
  
cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - secure: "LaAnT3XiwIKIP8MT5Nr1eZHjZJNTuitR8Dq1xsde0vC8Db3o9f727nOM/C/WjAnbJv+keASaNGV5QNM+oSU6WuYKs7OKqCWqZ72YNPHEyHcN0pt6XaX4nd+yloh6kRI7+ajhBhtE6JskbSeYq8vTQcAXglD5+E901NkUGtJ7XT9RbW1kXdwSs5+Gs4wCCKYRzwRi3CD/4LzCu8M0Qnr1liSyC8bg6a5KP8P88SZSMJOXnvcaHFppMtesIgUuQuGlaizjFfomx/YRNN+JuFL+nU/Ke8oJAyTkSeuoBJm4Q11fG7KSJhBul3B+DwASnNGqxWBnBAXkyOTdLZwb5XxtFIHbgWXecpdri6rxzY6nf9Av9oYkX84mx/JYWCw4h8YCHVHTzibSFhOSuphOtb+AQ9fXWYOQAX4366tAvkD7SS1+BBDqGgsbRdO/tS9hJ2ds2ThDryqZho3dtiyC8ltyF0GLRADwnhMJS+SlHRGE/sbuHk3FKc/sqg97EoHxzursdAurploMerMIKUGaB6BPGsmzwtR7fjGW1bXocsErsnkyOVUsB2pKXSt/AwjuWaQ/MjMAvd4o3PvXB9GznJ0U7fsrZhwEirnxH18GoaBf4smcqeA8UxuKoSly2HTPL9G2PcmBxLbliEN9RwigOIc5BTQOTaNi+6DTdeFq9B0A3gc="
    - secure: "3Jth/k+/i5EoCLRjuNPAN1mvvqT84+evsH/PWZDcOMOg85O+KgCiQg8jIzN9lcoZMrui9MQSJ2yvaQJ4d0SOTywfUwgMZl3rFe70x1/RNlZgK1cfYVoLMztpuOqZ8vzOrGiMvEur72KCPO5J7Y0A+Wovmu+NZFcXOYHGeguesbST1F8BnRMOWgiwJDkE4jg8CP6DyybcfhZUJQMZol5HBPcRnCxkCl1R6FLCM/GinOwdfWDPcGHiJ6jJCAYQNEwOJxh2325aCyP7sm4bgysFSQfTkd3iZ0wvQJojDZGoo4b4ulvM1yLuJWLhu39akjWE869ex9OZWK/ss4h9bhv0ydcokm95xyvBUk99r0CnqDkzbtl5GAtBweztWzrBft710MB1YiLPUpeKYemTv1a3XVCNcgaQAubeFoIA+nB226Zqm4kHylc+Ut0yXLDlSiLzf9vQn+G2t3o55wJ4le26uHmRhaWzayw55+P8TZTZQ+SbKwoNKceeIi6mD8in3uf1OVRtITKhDobc6eXoIiW/4vgfYrtRc9gkBxakEw2vj6vOfdHCbnFOnTmmDVyKSzU/GCoglUxZfb3jpH6RdB3099b4ZVoWaSi09bS8s3gnpHKObpd6tiGcWXyR93NPbQ2307rwSpYRmNYlpIW46Lg/XwwgHc5ZmIeNzCJt5epxVgY="
    - secure: "AfaeNJIxBMbKoLu0I3leiEKLKc+xJKN6HbM2Y1DLwJq74tIrFzkVabp/eRT9/1j7fGvThYjx6wINNO01kCZSenvafQOT/+o3aWaMA1WTQ05VL4Bu0Zp1Dbc1B+SbTe/yi4TaTMuxVl9/zOYHHI355Z/0jpwRGWr4mGBU+oYI7fM1i1b6Ws0VeiAGam2X8s7eFVpnMCCIR5NmtMkteRnvtX+JehG0HrQUxvEl/0Y+ewBtsXnxPwhavdKi4LENwkKkby1D7CsKnzbYGtPiwJ0NAe3p8gkiEZvLGBEJk5rTuz2T/5ORpei4+Fp2OFc5CjS1CMRc/O3RxY61s7fs3FA9lTkiR1vKwlhWrmKu2QAmHUoJ45pv/ybECNsuY4ViSpJGqDZwHCsh/dfzOf+G3pxOTbFJpxIkii0KG9r75oQoonEKYzcUyG0FiNvvg0R2rfxHpY7px3G5/v8/P61wee8QBTgDb/88QAZ+bTrfqZRrmSLYrif3LYx51JqooXbY8a1h125FGIi91sZiwAoDjdDZt8y4dgw09JmAlVzGhJxMGRlmLLz49gV5BXdrco3UAQw6M2FvhHdRN0XtrqXPsDDGI5ZlXjn/hq9VVsOfVg9n2bTHnMAlRAsQhFsGr2QZlhuDf4Z1MN2U8Adz8tLPOFkJepM/zv87HkzHgfj8RBxB4lc="
    - COMMIT=${TRAVIS_COMMIT::8}


after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - ci/deliver.sh

